/**
 * Metadata for all 16 OBD-II sensor inputs.
 * Used by the prediction form for labels, tooltips, units, and validation.
 */
export const SENSORS = [
  {
    key: "RPM",
    label: "Engine RPM",
    unit: "rpm",
    min: 0,
    max: 8000,
    step: 10,
    default: 800,
    tooltip: "Revolutions Per Minute — how fast the engine crankshaft is spinning. Idle is typically 600–900 RPM; highway driving ranges 1500–3000 RPM.",
    icon: "⚙️",
    category: "Engine",
  },
  {
    key: "SPEED",
    label: "Vehicle Speed",
    unit: "km/h",
    min: 0,
    max: 300,
    step: 1,
    default: 0,
    tooltip: "Current vehicle speed in km/h as reported by the wheel speed sensor or transmission.",
    icon: "🚗",
    category: "Engine",
  },
  {
    key: "THROTTLE_POS",
    label: "Throttle Position",
    unit: "%",
    min: 0,
    max: 100,
    step: 0.1,
    default: 15,
    tooltip: "Absolute throttle valve opening (0% = fully closed, 100% = wide open). Idle is typically 10–20%.",
    icon: "🎛️",
    category: "Throttle",
  },
  {
    key: "MAF",
    label: "Mass Air Flow",
    unit: "g/s",
    min: 0,
    max: 300,
    step: 0.1,
    default: 3.5,
    tooltip: "Mass Air Flow sensor measures grams of air entering the engine per second. Low values (2–5 g/s) at idle; higher under load.",
    icon: "💨",
    category: "Air",
  },
  {
    key: "SHORT_FUEL_TRIM_1",
    label: "Short-Term Fuel Trim 1",
    unit: "%",
    min: -30,
    max: 30,
    step: 0.1,
    default: 0,
    tooltip: "Short-term adjustment the ECU makes to the fuel mixture in real time. Values near 0% are ideal; large deviations (±10%) indicate fuel delivery issues.",
    icon: "⛽",
    category: "Fuel",
  },
  {
    key: "COOLANT_TEMP",
    label: "Coolant Temperature",
    unit: "°C",
    min: -40,
    max: 215,
    step: 1,
    default: 90,
    tooltip: "Engine coolant temperature. Normal operating range is 80–105°C. Above 110°C indicates overheating risk.",
    icon: "🌡️",
    category: "Thermal",
  },
  {
    key: "INTAKE_TEMP",
    label: "Intake Air Temperature",
    unit: "°C",
    min: -40,
    max: 215,
    step: 1,
    default: 30,
    tooltip: "Temperature of air entering the intake manifold. Affects fuel mixture calculation. High intake temps reduce engine efficiency.",
    icon: "🌬️",
    category: "Air",
  },
  {
    key: "LONG_FUEL_TRIM_1",
    label: "Long-Term Fuel Trim 1",
    unit: "%",
    min: -30,
    max: 30,
    step: 0.1,
    default: 0,
    tooltip: "Learned, long-term fuel mixture correction stored in ECU memory. Persistent deviations from 0% suggest intake leaks, dirty injectors, or sensor faults.",
    icon: "📊",
    category: "Fuel",
  },
  {
    key: "ENGINE_LOAD",
    label: "Engine Load",
    unit: "%",
    min: 0,
    max: 100,
    step: 0.1,
    default: 25,
    tooltip: "Calculated engine load as a percentage of maximum capacity. Idle is 20–30%; heavy load (climbing hills) can reach 80–100%.",
    icon: "📈",
    category: "Engine",
  },
  {
    key: "FUEL_LEVEL",
    label: "Fuel Level",
    unit: "%",
    min: 0,
    max: 100,
    step: 1,
    default: 60,
    tooltip: "Current fuel tank level as a percentage. Running below 10% regularly can damage the fuel pump.",
    icon: "🛢️",
    category: "Fuel",
  },
  {
    key: "ELM_VOLTAGE",
    label: "ELM Adapter Voltage",
    unit: "V",
    min: 0,
    max: 20,
    step: 0.01,
    default: 13.8,
    tooltip: "Battery/charging system voltage measured by the OBD adapter. Normal running range is 13.5–14.7 V. Below 12 V indicates a weak battery or alternator fault.",
    icon: "🔋",
    category: "Electrical",
  },
  {
    key: "FUEL_USAGE_ML_MIN",
    label: "Fuel Usage Rate",
    unit: "mL/min",
    min: 0,
    max: 2000,
    step: 0.1,
    default: 50,
    tooltip: "Instantaneous fuel consumption rate in milliliters per minute. Calculated from injector duty cycle and fuel pressure.",
    icon: "💧",
    category: "Fuel",
  },
  {
    key: "FUEL_USED_TOTAL_ML",
    label: "Total Fuel Used",
    unit: "mL",
    min: 0,
    max: 999999,
    step: 1,
    default: 500,
    tooltip: "Cumulative fuel consumed since the current ignition cycle started, in milliliters.",
    icon: "🏁",
    category: "Fuel",
  },
  {
    key: "RELATIVE_THROTTLE_POS",
    label: "Relative Throttle Position",
    unit: "%",
    min: 0,
    max: 100,
    step: 0.1,
    default: 10,
    tooltip: "Throttle opening relative to the closed-throttle baseline (learned by the ECU). Helps detect throttle plate carbon build-up.",
    icon: "🎚️",
    category: "Throttle",
  },
  {
    key: "ABSOLUTE_LOAD",
    label: "Absolute Engine Load",
    unit: "%",
    min: 0,
    max: 100,
    step: 0.1,
    default: 20,
    tooltip: "Normalized air mass per cylinder intake stroke as a percentage of maximum. More accurate than THROTTLE_POS for diesel/turbo engines.",
    icon: "💪",
    category: "Engine",
  },
  {
    key: "INTAKE_PRESSURE",
    label: "Intake Manifold Pressure",
    unit: "kPa",
    min: 0,
    max: 300,
    step: 0.1,
    default: 35,
    tooltip: "Absolute pressure in the intake manifold (MAP sensor). Vacuum engines: 20–100 kPa at idle; turbocharged engines can exceed 200 kPa under boost.",
    icon: "🔬",
    category: "Air",
  },
];

export const SENSOR_CATEGORIES = [...new Set(SENSORS.map((s) => s.category))];

export const RISK_CONFIG = {
  Healthy:   { color: "#22c55e", bg: "bg-green-500",  text: "text-green-400",  border: "border-green-500",  range: "75–100" },
  Moderate:  { color: "#eab308", bg: "bg-yellow-500", text: "text-yellow-400", border: "border-yellow-500", range: "50–75"  },
  "High Risk": { color: "#f97316", bg: "bg-orange-500", text: "text-orange-400", border: "border-orange-500", range: "25–50" },
  Critical:  { color: "#ef4444", bg: "bg-red-500",    text: "text-red-400",    border: "border-red-500",    range: "0–25"   },
};
